#ifndef MACRO_LUA_GAME
#error  Define MACRO_LUA_GAME before including this file.
#endif

MACRO_LUA_GAME(AppointHero,         appoint_hero)
MACRO_LUA_GAME(GenerateOwnUnit,     generate_own_unit)
MACRO_LUA_GAME(GenerateUnit,        generate_unit)
MACRO_LUA_GAME(ObtainEquipment,     obtain_equipment)
MACRO_LUA_GAME(GetNumEnemiesAlive,  get_num_enemies_alive)
MACRO_LUA_GAME(GetNumOwnsAlive,     get_num_owns_alive)
MACRO_LUA_GAME(PushCmdMove,         push_cmd_move)
MACRO_LUA_GAME(GetNumCommandersAlive, get_num_commanders_alive)
MACRO_LUA_GAME(GetTurnCurrent,       get_turn_current)
MACRO_LUA_GAME(HasUnit,              has_unit)
MACRO_LUA_GAME(GetNumUnitsAlive,     get_num_units_alive)
MACRO_LUA_GAME(AreUnitsWithin,       are_units_within)
MACRO_LUA_GAME(IsCellVacant,        is_cell_vacant)
MACRO_LUA_GAME(IsForceWithin,        is_force_within)
MACRO_LUA_GAME(IsUnitWithin,         is_unit_within)
MACRO_LUA_GAME(PushCmdSpeak,        push_cmd_speak)
MACRO_LUA_GAME(SetUnitInvulnerable, set_unit_invulnerable)
MACRO_LUA_GAME(SetForceDirection,   set_force_direction)
MACRO_LUA_GAME(SetUnitDirection,    set_unit_direction)

